# Generated by Django 4.2.4 on 2023-08-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_models',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
